#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.3 effective-5.10 (swiftlang-6.2.3.3.21 clang-1700.6.3.2)
#ifndef NESTADSSDK_SWIFT_H
#define NESTADSSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="NestAdsSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC10NestAdsSDK14NestAdsAdError")
@interface NestAdsAdError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10NestAdsSDK15NestAdsAdLoader")
@interface NestAdsAdLoader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP10NestAdsSDK23NestAdsAdLoaderDelegate_")
@protocol NestAdsAdLoaderDelegate
- (void)adLoader:(NestAdsAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NestAdsAdError * _Nonnull)error;
@optional
- (void)adLoaderDidFinishLoading:(NestAdsAdLoader * _Nonnull)adLoader;
@end

@class NSCoder;
SWIFT_CLASS("_TtC10NestAdsSDK23NestAdsCardBannerAdView")
@interface NestAdsCardBannerAdView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UICollectionView;
@class NSIndexPath;
@class UICollectionViewCell;
@class UICollectionViewLayout;
@class UIScrollView;
@interface NestAdsCardBannerAdView (SWIFT_EXTENSION(NestAdsSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

SWIFT_CLASS("_TtC10NestAdsSDK24NestAdsImageBannerAdView")
@interface NestAdsImageBannerAdView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)didMoveToSuperview;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC10NestAdsSDK16NestAdsMediaView")
@interface NestAdsMediaView : UIView
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)didMoveToWindow;
- (void)didMoveToSuperview;
@end

@class NestAdsOfferwallQuizFactory;
@class NestAdsOfferwallMissionFactory;
@class UIApplication;
@class NSString;
@class NSNumber;
@class UIViewController;
/// 오퍼월 기능을 제공하는 브릿지 클래스
/// NestAdsOfferwallSDK를 런타임에 동적으로 로드하고 관리
SWIFT_CLASS("_TtC10NestAdsSDK22NestAdsOfferwallBridge")
@interface NestAdsOfferwallBridge : NSObject
/// Quiz 인스턴스 생성 Factory
@property (nonatomic, strong) NestAdsOfferwallQuizFactory * _Nonnull quiz;
/// Mission 인스턴스 생성 Factory
@property (nonatomic, strong) NestAdsOfferwallMissionFactory * _Nonnull mission;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 오퍼월 초기화
/// \param application UIApplication 객체
///
/// \param appKey AdChain 앱 키
///
/// \param appSecret AdChain 앱 시크릿
///
/// \param environment 환경 설정 (기본값: “production”)
///
/// \param timeoutMillis 네트워크 타임아웃 (밀리초 단위, nil이면 AdChain SDK 기본값 사용)
///
- (void)initializeWithApplication:(UIApplication * _Nonnull)application appKey:(NSString * _Nonnull)appKey appSecret:(NSString * _Nonnull)appSecret environment:(NSString * _Nonnull)environment timeoutMillis:(NSNumber * _Nullable)timeoutMillis;
/// Objective-C 호환: 로그인
/// \param userId 사용자 ID
///
/// \param gender 성별 (NestAdsGenderUnknown, NestAdsGenderMale, NestAdsGenderFemale)
///
/// \param birthYear 출생 연도 (선택)
///
- (void)loginWithUserId:(NSString * _Nonnull)userId gender:(NSInteger)gender birthYear:(NSNumber * _Nullable)birthYear;
/// 로그아웃
- (void)logout;
/// 오퍼월 표시
/// \param viewController 표시할 뷰 컨트롤러
///
/// \param placementCode 플레이스먼트 코드
///
/// \param showNavigationBar 네비게이션 바 표시 여부 (기본값: false)
///
/// \param useNativeNavigationBar 네이티브 네비게이션 바 사용 여부 (기본값: false)
///
/// \param delegate 오퍼월 이벤트 delegate (optional)
///
- (void)openOfferwallFrom:(UIViewController * _Nonnull)viewController placementCode:(NSString * _Nonnull)placementCode showNavigationBar:(BOOL)showNavigationBar useNativeNavigationBar:(BOOL)useNativeNavigationBar delegate:(id _Nullable)delegate;
/// 오퍼월 초기화 여부
@property (nonatomic, readonly) BOOL isInitialized;
/// 오퍼월 로그인 여부
@property (nonatomic, readonly) BOOL isLoggedIn;
/// 현재 사용자 ID
@property (nonatomic, readonly, copy) NSString * _Nonnull currentUserId;
/// SDK 버전
@property (nonatomic, readonly, copy) NSString * _Nonnull sdkVersion;
/// AdChain SDK 버전
@property (nonatomic, readonly, copy) NSString * _Nonnull adchainSDKVersion;
@end

@class NSError;
/// NestAdsOfferwallSDK 런타임 연결 인터페이스
/// NestAdsSDK가 NestAdsOfferwallSDK를 직접 의존하지 않고
/// 런타임에 동적으로 로드하기 위한 프로토콜
SWIFT_PROTOCOL("_TtP10NestAdsSDK25NestAdsOfferwallInterface_")
@protocol NestAdsOfferwallInterface <NSObject>
/// 오퍼월 초기화
/// \param appKey AdChain 앱 키
///
/// \param appSecret AdChain 앱 시크릿
///
/// \param environment 환경 설정
///
/// \param completion 초기화 완료 핸들러
///
- (void)initializeOfferwallWithAppKey:(NSString * _Nonnull)appKey appSecret:(NSString * _Nonnull)appSecret environment:(NSString * _Nonnull)environment completion:(void (^ _Nullable)(BOOL, NSError * _Nullable))completion;
/// 로그인
/// \param userId 사용자 ID
///
/// \param gender 성별
///
/// \param birthYear 출생 연도
///
/// \param delegate 로그인 이벤트 콜백
///
- (void)loginOfferwallWithUserId:(NSString * _Nonnull)userId gender:(NSString * _Nullable)gender birthYear:(NSNumber * _Nullable)birthYear delegate:(id <NSObject> _Nullable)delegate;
/// 로그아웃
- (void)logoutOfferwall;
/// 오퍼월 표시
/// \param viewController 표시할 뷰 컨트롤러
///
/// \param placementId 플레이스먼트 ID
///
/// \param delegate 오퍼월 이벤트 콜백
///
- (void)openOfferwallFrom:(UIViewController * _Nonnull)viewController placementId:(NSString * _Nonnull)placementId delegate:(id <NSObject> _Nullable)delegate;
/// 커스텀 URL 오퍼월 표시
/// \param viewController 표시할 뷰 컨트롤러
///
/// \param url 오퍼월 URL
///
/// \param placementId 플레이스먼트 ID
///
/// \param showNavigationBar 네비게이션 바 표시 여부
///
/// \param delegate 오퍼월 이벤트 콜백
///
- (void)openOfferwallWithUrlFrom:(UIViewController * _Nonnull)viewController url:(NSString * _Nonnull)url placementId:(NSString * _Nonnull)placementId showNavigationBar:(BOOL)showNavigationBar delegate:(id <NSObject> _Nullable)delegate;
/// Adjoe 오퍼월 표시
/// \param viewController 표시할 뷰 컨트롤러
///
/// \param placementId 플레이스먼트 ID
///
/// \param delegate 오퍼월 이벤트 콜백
///
- (void)openAdjoeOfferwallFrom:(UIViewController * _Nonnull)viewController placementId:(NSString * _Nonnull)placementId delegate:(id <NSObject> _Nullable)delegate;
/// 오퍼월 초기화 여부
@property (nonatomic, readonly) BOOL isOfferwallInitialized;
/// 오퍼월 로그인 여부
@property (nonatomic, readonly) BOOL isOfferwallLoggedIn;
/// 현재 사용자 ID
@property (nonatomic, readonly, copy) NSString * _Nullable offerwallCurrentUserId;
/// SDK 버전
@property (nonatomic, readonly, copy) NSString * _Nonnull offerwallSDKVersion;
/// AdChain SDK 버전
@property (nonatomic, readonly, copy) NSString * _Nonnull adchainSDKVersion;
@end

/// Wrapper for AdChain SDK’s AdchainMission
/// Created by users via NestAds.Offerwall.Mission()
SWIFT_CLASS("_TtC10NestAdsSDK23NestAdsOfferwallMission")
@interface NestAdsOfferwallMission : NSObject
/// Load mission data via Delegate callback
- (void)load;
/// Click mission by mission ID
/// \param missionId Mission ID
///
/// \param viewController View controller to display
///
- (void)clickMission:(NSString * _Nonnull)missionId from:(UIViewController * _Nonnull)viewController;
/// Trigger reward button click event
/// \param viewController View controller to present reward UI
///
- (void)triggerRewardButtonClickFrom:(UIViewController * _Nonnull)viewController;
/// Refresh mission list
/// \param unitId Unit ID (optional)
///
- (void)refreshMissionListWithUnitId:(NSString * _Nullable)unitId;
/// Clean up mission resources
- (void)destroy;
/// Set mission event delegate
/// \param delegate Object implementing NestAdsOfferwallMissionDelegate
///
- (void)setDelegate:(id _Nonnull)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Factory for creating Mission instances
/// Uses @dynamicCallable to enable Mission() syntax
SWIFT_CLASS("_TtC10NestAdsSDK30NestAdsOfferwallMissionFactory")
@interface NestAdsOfferwallMissionFactory : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Wraps AdChain SDK’s AdchainQuiz
/// Used by NestAds.Offerwall.Quiz()
SWIFT_CLASS("_TtC10NestAdsSDK20NestAdsOfferwallQuiz")
@interface NestAdsOfferwallQuiz : NSObject
/// Load quiz data via Delegate callback
- (void)load;
/// Click quiz by quizId
/// \param quizId Quiz ID
///
/// \param viewController View controller to display
///
- (void)clickQuiz:(NSString * _Nonnull)quizId from:(UIViewController * _Nonnull)viewController;
/// Set quiz event delegate
/// \param delegate Object implementing NestAdsOfferwallQuizDelegate
///
- (void)setDelegate:(id _Nonnull)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Factory for creating Quiz instances
/// Uses @dynamicCallable to enable Quiz() syntax
SWIFT_CLASS("_TtC10NestAdsSDK27NestAdsOfferwallQuizFactory")
@interface NestAdsOfferwallQuizFactory : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC10NestAdsSDK18NestAdsPopupAdView")
@interface NestAdsPopupAdView : UIView
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface NestAdsPopupAdView (SWIFT_EXTENSION(NestAdsSDK)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * _Nonnull)collectionView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)numberOfItemsInSection SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
@end

SWIFT_CLASS("_TtC10NestAdsSDK26NestAdsPremiumBannerAdView")
@interface NestAdsPremiumBannerAdView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC10NestAdsSDK19NestAdsSplashAdView")
@interface NestAdsSplashAdView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_CLASS("_TtC10NestAdsSDK22NestAdsVideoController")
@interface NestAdsVideoController : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP10NestAdsSDK30NestAdsVideoControllerDelegate_")
@protocol NestAdsVideoControllerDelegate
@optional
- (void)videoControllerDidCompletePreparation;
- (void)videoControllerDidPlayVideo;
- (void)videoControllerDidPauseVideo;
- (void)videoControllerDidEndVideoPlayback;
- (void)videoControllerDidMuteVideo:(NestAdsVideoController * _Nonnull)videoController;
- (void)videoControllerDidUnmuteVideo:(NestAdsVideoController * _Nonnull)videoController;
- (void)videoControllerDidUpdateVideoProgressWithCurrent:(NSTimeInterval)current;
- (void)videoControllerDidFailToLoadVideo;
- (void)videoControllerDidFailToLoadVideoWithErrorDescription:(NSString * _Nonnull)errorDescription;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
